rootProject.name = "28-08-23-java-otus-pro"
include("hw01-gradle")
include("hw2")
include("hw04-collection")
include("hw06-annotation")
include("hw08-gc")
include("hw10-bc")
include("hw12-oop")
include("hw15")
include("hw16-json")
include("hw19-jdbc")
include("hw21-jpql")
include("hw22")
include("hw24-webServer")
include("hw22-cache")
