server:
  port: 8189

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
  liquibase:
    change-log: classpath:/liquibase/changelog-master.yml
logging:
  level:
    ROOT: ERROR

application:
  avatars-dir-name:
    ./avatars
