server:
  port: 8189

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234

  jpa:
      database: POSTGRESQL
      show-sql: true
      hibernate:
        ddl-auto: create-drop

  liquibase:
    change-log: classpath:/liquibase/changelog-master.yml
logging:
  level:
    ROOT: INFO

application:
  avatars-dir-name:
    ./avatars
